# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFrame4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_frame4(self):
    self.driver.get("http://192.168.43.108/login")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-input__inner").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys("Admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".el-col:nth-child(2) > .output-wrap > .output-nav .el-icon-setting").click()
    self.vars["num"] = self.driver.execute_script("return 1")
    condition = True
    while condition:
      self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-select .el-input__inner").click()
      self.driver.find_element(By.XPATH, "//span[contains(.,\'1920x1080P 60Hz\')]").click()
      self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(5) span").click()
      self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-select .el-input__inner").click()
      self.driver.find_element(By.XPATH, "//li[15]/span").click()
      self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(5) > .el-button").click()
      self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-select .el-input__inner").click()
      self.driver.find_element(By.XPATH, "//span[contains(.,\'1920x1080P 25Hz\')]").click()
      self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(5) > .el-button").click()
      self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-select .el-input__inner").click()
      self.driver.find_element(By.XPATH, "//li[contains(.,\'1920x1080i 60Hz\')]").click()
      self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(5) span").click()
      self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-select .el-input__inner").click()
      self.driver.find_element(By.XPATH, "//li[8]/span").click()
      self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(5) > .el-button").click()
      element = self.driver.find_element(By.CSS_SELECTOR, ".el-drawer__open #el-drawer__title .el-dialog__close")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      condition = self.driver.execute_script("return (arguments[0]<2000)", self.vars["num"])
    self.driver.find_element(By.CSS_SELECTOR, ".el-drawer__open #el-drawer__title .el-dialog__close").click()
  
